export const SET_LINE_BY_MONTH_DATA_CHART = "SET_LINE_BY_MONTH_DATA_CHART";
export const GET_LINE_BY_MONTH_DATA_CHART = "GET_LINE_BY_MONTH_DATA_CHART";
export const SET_LINE_BY_DATE_DATA_CHART = "SET_LINE_BY_DATE_DATA_CHART";
export const GET_LINE_BY_DATE_DATA_CHART = "GET_LINE_BY_DATE_DATA_CHART";
export const SET_BUS_BY_DATE_DATA_CHART = "SET_BUS_BY_DATE_DATA_CHART";
export const GET_BUS_BY_DATE_DATA_CHART = "GET_BUS_BY_DATE_DATA_CHART";
export const SET_UNIT_BY_DATE_DATA_CHART = "SET_UNIT_BY_DATE_DATA_CHART";
export const GET_UNIT_BY_DATE_DATA_CHART = "GET_UNIT_BY_DATE_DATA_CHART";

