export const SET_LINE_BY_DATE_DATA_CHART = "SET_LINE_BY_DATE_DATA_CHART";
export const GET_LINE_BY_DATE_DATA_CHART = "GET_LINE_BY_DATE_DATA_CHART";
export const SET_LINE_BY_MONTH_DATA_CHART = "SET_LINE_BY_MONTH_DATA_CHART";
export const GET_LINE_BY_MONTH_DATA_CHART = "GET_LINE_BY_MONTH_DATA_CHART";