export const SET_TRANSPORTER_LIST = 'SET_TRANSPORTER_LIST';
export const SET_TRANSPORTER_LINE_LIST = 'SET_TRANSPORTER_LINE_LIST';
export const SET_EDITING_TRANSPORTER = 'SET_EDITING_TRANSPORTER';
export const GET_TRANSPORTER_LIST_API = 'GET_TRANSPORTER_LIST_API';
export const DELETE_TRANSPORTER_API = 'DELETE_TRANSPORTER_API';
export const ADD_TRANSPORTER_API = 'ADD_TRANSPORTER_API';
export const UPDATE_TRANSPORTER_API = 'UPDATE_TRANSPORTER_API';