export const SET_DOCUMENT_LIST = "SET_DOCUMENT_LIST";
export const GET_DOCUMENT_LIST_API = "GET_DOCUMENT_LIST_API";
export const ADD_DOCUMENT_API = "ADD_DOCUMENT_API";
export const DELETE_DOCUMENT_API = "DELETE_DOCUMENT_API";
export const SET_DOCUMENT_EDITING ="SET_DOCUMENT_EDITING";